### ISSUE TITLE
Rename Visual Studio Team Services to Azure DevOps Services

### ISSUE THREAD

**Issue by GarethOates** [Microsoft/GVFS.www#11]
In relation to [VSTS being renamed AzureDevOps Services](https://docs.microsoft.com/en-us/azure/devops/user-guide/what-happened-vsts?view=vsts) the website should be updated to include the new branding/naming.

I had hoped to swap out the logo but couldn't find one for Azure DevOps services yet.

- [x] Replace references to VSTS with Azure DevOps
- [ ] Update logo

**Comment by ethomson** [comment]
Thanks!  Now that I've got vfsforgit.org finally set up, we've fixed this as well.
